name: "Install SP1"
description: "Install SP1 Toolchain"

runs:
  using: "composite"
  steps:
    - name: Cache SP1 toolchain
      uses: actions/cache@v4
      id: sp1-cache
      with:
        path: ~/.sp1
        key: sp1-toolchain-5.0.8

    - name: Install SP1
      if: steps.sp1-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -L https://sp1up.succinct.xyz | bash
        ~/.sp1/bin/sp1up --version 5.0.8
