name: "Install SP1"
description: "Install SP1 Toolchain"

runs:
  using: "composite"
  steps:
    - name: Install SP1
      shell: bash
      run: |
        curl -L https://sp1up.succinct.xyz | bash
        ~/.sp1/bin/sp1up --version 5.0.8
