name: "Install RISC0"
description: "Install RISC0 Toolchain"

# When updating the RISC0 version, update BOTH:
#   1. The cache key (line 12)
#   2. The rzup install versions (lines 19, 23)

runs:
  using: "composite"
  steps:
    - name: Cache RISC0 toolchain
      uses: actions/cache@v4
      id: risc0-cache
      with:
        path: |
          ~/.risc0
          ~/.rustup/toolchains/risc0
        key: risc0-toolchain-3.0.3-v2

    - name: Install RISC0
      if: steps.risc0-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        ~/.risc0/bin/rzup install cargo-risczero 3.0.3
        ~/.risc0/bin/rzup install risc0-groth16
        ~/.risc0/bin/rzup install rust
        ~/.risc0/bin/rzup install cpp
        ~/.risc0/bin/rzup install r0vm 3.0.3
