name: "Install ZisK"
description: "Install ZisK Toolchain"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xz-utils jq curl build-essential qemu-system libomp-dev libgmp-dev nlohmann-json3-dev protobuf-compiler uuid-dev libgrpc++-dev libsecp256k1-dev libsodium-dev libpqxx-dev nasm libopenmpi-dev openmpi-bin openmpi-common libclang-dev clang gcc-riscv64-unknown-elf

    - name: Install ZisK
      shell: bash
      env:
        SETUP_KEY: none
      run: |
        curl https://raw.githubusercontent.com/0xPolygonHermez/zisk/v0.14.0/ziskup/install.sh | bash

    - name: Add ZisK to PATH
      shell: bash
      run: echo "$HOME/.zisk/bin" >> $GITHUB_PATH
