name: "Install Pico"
description: "Install Pico Toolchain"

runs:
  using: "composite"
  steps:
    - name: Install Pico
      run: |
        rustup install nightly-2025-08-04
        rustup component add rust-src --toolchain nightly-2025-08-04
        cargo +nightly-2025-08-04 install --git https://github.com/brevis-network/pico --tag v1.1.9 pico-cli
