name: PR Github Metadata

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  assign-author:
    name: Assign Author
    if: github.event.action == 'opened' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR author
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.pull_request.user.login]
            });

  label-pr:
    name: Set Labels
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply labels from PR title
        uses: actions/github-script@v7
        with:
          script: |
            const run = require('./.github/scripts/set-pr-labels.js');
            await run({ github, context });
