name: Replay Test
permissions:
  contents: read
on:
  # For now on every push so that i test it
  push:
    branches: ["**"]
  # pull_request:
  #   branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Execute an L1 block with ${{ matrix.backend }} backend
    strategy:
      fail-fast: false
      matrix:
        backend: ["sp1", "risc0", "exec"]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: RISC-V Risc0 toolchain install
        if: matrix.backend == 'risc0'
        # should be able to specify a version for `rzup install rust` (toolchain version)
        # but it throws a "error decoding response body" in that case
        run: |
          curl -L https://risczero.com/install | bash
          ~/.risc0/bin/rzup install cargo-risczero 3.0.3
          ~/.risc0/bin/rzup install risc0-groth16
          ~/.risc0/bin/rzup install rust

      - name: RISC-V SP1 toolchain install
        if: matrix.backend == 'sp1'
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version 5.0.8

      - name: Build Risc0
        if: matrix.backend == 'risc0'
        run: |
          cargo b -r --no-default-features --features "${{ matrix.backend }}"

      - name: Build SP1
        if: matrix.backend == 'sp1'
        run: |
          cargo b -r --features "${{ matrix.backend }}"

      - name: Build No backend
        if: matrix.backend == 'exec'
        run: |
          cargo b -r

      - name: Run
        env:
          BLOCK_NUMBER: 1265656
          NETWORK: hoodi
        run: |
          # Install cache file before running
          install -D caches/cache_hoodi_${BLOCK_NUMBER}.json replay_cache/cache_hoodi_${BLOCK_NUMBER}.json

          if [ "${{ matrix.backend }}" = "exec" ]; then
            make execute-ci BLOCK_NUMBER=${BLOCK_NUMBER} NETWORK=${NETWORK}
          else
            make execute-${{ matrix.backend }}-ci BLOCK_NUMBER=${BLOCK_NUMBER} NETWORK=${NETWORK}
          fi

  all-tests:
    # Integration Test is required check, don't change the name
    name: Integration Test
    runs-on: ubuntu-latest
    needs:
      - test
    # Run regardless of matrix outcome so this job can report overall status
    if: ${{ always() }}
    steps:
      - name: Aggregate test results
        run: |
          if [ "${{ needs.test.result }}" = "success" ]; then
            echo "All test jobs succeeded."
            exit 0
          fi
          echo "Some test jobs failed" >&2
          exit 1
