name: Replay Lint
permissions:
  contents: read
on:
  # For now on every push so that i test it
  push:
    branches: ["**"]
  # pull_request:
  #   branches: ["**"]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        features: ["", "l2", "l2,sp1", "l2,risc0", "sp1", "risc0"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Install clippy
        run: rustup component add clippy

      - name: RISC-V Risc0 toolchain install
        if: contains(matrix.features, 'risc0')
        run: |
          curl -L https://risczero.com/install | bash
          ~/.risc0/bin/rzup install cargo-risczero 3.0.3
          ~/.risc0/bin/rzup install risc0-groth16
          ~/.risc0/bin/rzup install rust

      - name: cargo fmt --check --all
        if: matrix.features == '' # Run only without features because it's redundant to run it on all jobs
        run: cargo fmt --check --all

      - name: cargo check
        shell: bash
        env:
          FEATURE_ARGS: ${{ matrix.features }}
        run: |
          set -euxo pipefail
          args=(--release --no-default-features)
          if [ -n "${FEATURE_ARGS}" ]; then
            args+=("--features" "${FEATURE_ARGS}")
          fi
          cargo check "${args[@]}"

      - name: cargo clippy
        shell: bash
        env:
          FEATURE_ARGS: ${{ matrix.features }}
        run: |
          set -euxo pipefail
          args=(--release --no-default-features)
          if [ -n "${FEATURE_ARGS}" ]; then
            args+=("--features" "${FEATURE_ARGS}")
          fi
          cargo clippy "${args[@]}" -- -D warnings

  all-lints:
    # The purpose of this job is to add it as a required check in GitHub so that we don't have to add every individual job as a required check
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - lint
    # Run regardless of matrix outcome so this job can report overall status
    if: ${{ always() }}
    steps:
      - name: Aggregate lint results
        run: |
          if [ "${{ needs.lint.result }}" = "success" ]; then
            echo "All lint jobs succeeded."
            exit 0
          fi
          echo "Some lint jobs failed" >&2
          exit 1
