name: Replay Basic Run

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Build with Cargo
        run: cargo run -- block 1281069 --cache-dir ./caches --network hoodi --cached
