name: Replay Workflow Call

on:
  workflow_call:
    inputs:
      ethrex_branch:
        description: "Branch name of ethrex repo that invoked this workflow"
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Decide replay ref from ethrex branch
        id: pick_ref
        shell: bash
        env:
          ETHREX_BRANCH: ${{ inputs.ethrex_branch }}
        run: |
          # Policy: try "ethrex/<ethrex_branch>", else fall back to main branch
          CANDIDATE="ethrex/$ETHREX_BRANCH"

          if git ls-remote --exit-code --heads https://github.com/lambdaclass/ethrex-replay.git "$CANDIDATE" >/dev/null; then
            echo "ref=$CANDIDATE" >> "$GITHUB_OUTPUT"
            echo "Picked replay branch: $CANDIDATE"
            exit 0
          fi

          # Fallback (stable default)
          echo "ref=add_remote_workflow" >> "$GITHUB_OUTPUT"
          echo "No matching branch found; falling back to add_remote_workflow"

      - name: Checkout called repo
        uses: actions/checkout@v4
        with:
          repository: lambdaclass/ethrex-replay
          ref: ${{ steps.pick_ref.outputs.ref }}

      - name: Update Cargo.toml dependency branch
        shell: bash
        run: |
          branch='${{ inputs.ethrex_branch }}'
          sed -i "/ethrex/s/branch = \"main\"/branch = \"$branch\"/" Cargo.toml

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Run block
        run: cargo run -- block 1265656 --cache-dir ./caches --network hoodi --cached

      - name: Help: Replay CI failure troubleshooting
        if: ${{ failure() }}
        env:
          ETHREX_BRANCH: ${{ inputs.ethrex_branch }}
          PICKED_REF: ${{ steps.pick_ref.outputs.ref }}
        shell: bash
        run: |
          echo "Replay workflow failed for ethrex branch: ${ETHREX_BRANCH}" >&2
          echo "Replay ref used (branch or fallback): ${PICKED_REF}" >&2
          echo "If this failure is due to a branch mismatch, see the Ethrex ↔ Replay CI guide:" >&2
          echo "https://github.com/lambdaclass/ethrex-replay/blob/main/docs/contributing-ethrex.md" >&2
          echo "Tip: create a matching replay branch named 'ethrex/${ETHREX_BRANCH}' if your ethrex changes require replay updates." >&2
