name: Replay Workflow Call

on:
  workflow_call:
    inputs:
      checkout_repo:
        description: "owner/name to operate on"
        required: true
        type: string
      checkout_ref:
        description: "Branch/tag/SHA to checkout"
        required: false
        type: string
        default: main
    secrets:
      REPO_TOKEN:
        description: "PAT with read access to checkout_repo (needed if private)"
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout called repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.checkout_repo }}
          ref: ${{ inputs.checkout_ref }}
          # For private repos, pass a PAT via secrets.REPO_TOKEN from the caller.
          # For public repos, this can fall back to github.token.
          token: ${{ secrets.REPO_TOKEN || github.token }}

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Run block
        run: cargo run -- block 1281069 --cache-dir ./caches --network hoodi --cached
