name: Replay Workflow Call

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ethrex-replay
    steps:
      - name: Checkout ethrex-replay sources
        uses: actions/checkout@v4
        with:
          repository: lambdaclass/ethrex-replay
          fetch-depth: 0
          path: ethrex-replay

      - name: Setup Rust Environment
        uses: ./ethrex-replay/.github/actions/setup-rust

      - name: Run block
        run: cargo run -- block 1281069 --cache-dir ./caches --network hoodi --cached
