name: Replay Workflow Call

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout called repo
        uses: actions/checkout@v4
        with:
          repository: lambdaclass/ethrex-replay
          ref: main

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Run block
        run: cargo run -- block 1265656 --cache-dir ./caches --network hoodi --cached
