name: Replay Workflow Call

on:
  workflow_call:

jobs:
  quick-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: lambdaclass/ethrex-replay
          ref: move_replay
          path: ethrex-replay

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust

      - name: Run block
        run: cargo run -- block 1281069 --cache-dir ./caches --network hoodi --cached
